
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcRestaurant.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class TBLİLETİSİM
{

    public int ID { get; set; }

    public string AD { get; set; }

    public string mail { get; set; }

    public string konu { get; set; }

    public string mesaj { get; set; }

}

}
