
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcRestaurant.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class TBLRezervasyon
{

    public int ID { get; set; }

    public string Yemeksecimi { get; set; }

    public string ad { get; set; }

    public string telefon { get; set; }

    public string personeladi { get; set; }

    public string rezervasyontarihi { get; set; }

    public string masano { get; set; }

    public string kisisayisi { get; set; }

    public string garsondurum { get; set; }

    public string sefdurum { get; set; }

    public string mailadresi { get; set; }

    public string İstekler { get; set; }

    public string maliyet { get; set; }

    public string satis { get; set; }

    public Nullable<int> kar { get; set; }

    public Nullable<int> satiss { get; set; }

}

}
